export const lessons = [
  {
    id: "animals",
    icon: "dog",
    title: "חיות",
    description: "מתרגלים שמות של חיות ומשפטים פשוטים.",
    word: "cat",
    question: 'איך אומרים "חתול" באנגלית?',
    answer: "cat",
    example: "The cat is small.",
    progress: 70,
  },
  {
    id: "colors",
    icon: "palette",
    title: "צבעים",
    description: "לומדים צבעים בעזרת תמונות ושאלות.",
    word: "blue",
    question: 'איך אומרים "כחול" באנגלית?',
    answer: "blue",
    example: "The sky is blue.",
    progress: 55,
  },
  {
    id: "weather",
    icon: "sun",
    title: "מזג אוויר",
    description: "מתרגלים מילים על מזג האוויר ושיחות קצרות.",
    word: "rain",
    question: 'איך אומרים "גשם" באנגלית?',
    answer: "rain",
    example: "I like rain.",
    progress: 45,
  },
];
